
# ⬇️  Change this to match the URL of your Outerbounds deployment
platform = "olyzon.obp.outerbounds.com"

# ⬇️  Change these to match your project name
project = "ob_test_project"
title = "Test Outerbounds Project"

# (optional) disable automatic application of a project-wide pyproject.toml
# [dependencies]
# include_pyproject_toml=false

# (optional) Enable this section to access assets in local runs
# [dev-assets]
# branch = 'dev'
# read-only = true
