
# ⬇️  Change this to match the URL of your Outerbounds deployment
platform = 'dev-silverwing.outerbounds.xyz'

# ⬇️  Change these to match your project name
project = 'ob_project_empty'
title = 'Empty Outerbounds Project'

# (optional) Enable this section to access assets in local runs
# [dev-assets]
# branch = 'dev'
# read-only = true
